# executing COG_diversity_calculations.py to extract accessory gene list from eggNOG mapping and calculate COG diversity
#within each category
# chromosome
python COG_diversity_calculations.py accessory_output/chromosome/Aliivibrio_genus/Aliivibrio_genus_95_gene_list_represenative.txt eggnog_mapping/chromosome/Aliivibrio_genus/Aliivibrio_genus.emapper.annotations COG_diversity_output/Aliivibrio_chromosome_COG_diversity.csv
python COG_diversity_calculations.py accessory_output/chromosome/Photobacterium_genus/Photobacterium_genus_95_gene_list_represenative.txt eggnog_mapping/chromosome/Photobacterium_genus/Photobacterium_genus.emapper.annotations COG_diversity_output/Photobacterium_chromosome_COG_diversity.csv
python COG_diversity_calculations.py accessory_output/chromosome/Pseudoalteromonas_genus/Pseudoalteromonas_genus_95_gene_list_represenative.txt eggnog_mapping/chromosome/Pseudoalteromonas_genus/Pseudoalteromonas_genus.emapper.annotations COG_diversity_output/Pseudoalteromonas_chromosome_COG_diversity.csv
python COG_diversity_calculations.py accessory_output/chromosome/Salinivibrio_genus/Salinivibrio_genus_95_gene_list_represenative.txt eggnog_mapping/chromosome/Salinivibrio_genus/Salinivibrio_genus.emapper.annotations COG_diversity_output/Salinivibrio_chromosome_COG_diversity.csv
python COG_diversity_calculations.py accessory_output/chromosome/Vibrio_genus/Vibrio_genus_95_gene_list_represenative.txt eggnog_mapping/chromosome/Vibrio_genus/Vibrio_genus.emapper.annotations COG_diversity_output/Vibrio_chromosome_COG_diversity.csv

# chromid
python COG_diversity_calculations.py accessory_output/chromid/Aliivibrio_genus/Aliivibrio_genus_95_gene_list_represenative.txt eggnog_mapping/chromid/Aliivibrio_genus/Aliivibrio_genus.emapper.annotations COG_diversity_output/Aliivibrio_chromid_COG_diversity.csv
python COG_diversity_calculations.py accessory_output/chromid/Photobacterium_genus/Photobacterium_genus_95_gene_list_represenative.txt eggnog_mapping/chromid/Photobacterium_genus/Photobacterium_genus.emapper.annotations COG_diversity_output/Photobacterium_chromid_COG_diversity.csv
python COG_diversity_calculations.py accessory_output/chromid/Pseudoalteromonas_genus/Pseudoalteromonas_genus_95_gene_list_represenative.txt eggnog_mapping/chromid/Pseudoalteromonas_genus/Pseudoalteromonas_genus.emapper.annotations COG_diversity_output/Pseudoalteromonas_chromid_COG_diversity.csv
python COG_diversity_calculations.py accessory_output/chromid/Vibrio_genus/Vibrio_genus_95_gene_list_represenative.txt eggnog_mapping/chromid/Vibrio_genus/Vibrio_genus.emapper.annotations COG_diversity_output/Vibrio_chromid_COG_diversity.csv

# megaplasmid
python COG_diversity_calculations.py accessory_output/megaplasmid/Pseudoalteromonas_genus/Pseudoalteromonas_genus_95_gene_list_represenative.txt eggnog_mapping/megaplasmid/Pseudoalteromonas_genus/Pseudoalteromonas_genus.emapper.annotations COG_diversity_output/Pseudoalteromonas_megaplasmid_COG_diversity.csv
python COG_diversity_calculations.py accessory_output/megaplasmid/Salinivibrio_genus/Salinivibrio_genus_95_gene_list_represenative.txt eggnog_mapping/megaplasmid/Salinivibrio_genus/Salinivibrio_genus.emapper.annotations COG_diversity_output/Salinivibrio_megaplasmid_COG_diversity.csv
python COG_diversity_calculations.py accessory_output/megaplasmid/Vibrio_genus/Vibrio_genus_95_gene_list_represenative.txt eggnog_mapping/megaplasmid/Vibrio_genus/Vibrio_genus.emapper.annotations COG_diversity_output/Vibrio_megaplasmid_COG_diversity.csv

# extrachromosomal (Pseudoalteromonas and VIbrio)
# calculating COGs diversity for extrachromosomal replicons
python COG_diversity_calculations.py \
    accessory_output/extrachromosomal/Pseudoalteromonas_genus/Pseudoalteromonas_genus_95_gene_list_represenative.txt \
    eggnog_mapping/extrachromosomal/Pseudoalteromonas_genus/Pseudoalteromonas_genus.emapper.annotations \
    COG_diversity_output/Pseudoalteromonas_extrachromosomal_COG_diversity.csv

python COG_diversity_calculations.py \
    accessory_output/extrachromosomal/Vibrio_genus/Vibrio_genus_95_gene_list_represenative.txt \
    eggnog_mapping/extrachromosomal/Vibrio_genus/Vibrio_genus.emapper.annotations \
    COG_diversity_output/Vibrio_extrachromosomal_COG_diversity.csv

# calculating COGs diversity for all genera
python COG_diversity_calculations.py \
    accessory_output/chromosome/All_genus/All_genus_95_gene_list_represenative.txt \
    eggnog_mapping/chromosome/All_genus/All_genus.emapper.annotations \
    COG_diversity_output/All_chromosome_COG_diversity.csv

python COG_diversity_calculations.py \
    accessory_output/extrachromosomal/All_genus/All_genus_95_gene_list_represenative.txt \
    eggnog_mapping/extrachromosomal/All_genus/All_genus.emapper.annotations \
    COG_diversity_output/All_extrachromosomal_COG_diversity.csv


