#extracting and counting COG categories from emapper result and query_pan_genome represenativa gene list

#copying emapper output for backup
cp -R eggnog_mapping/ eggnog_mapping_backup

# calculating COGs for given replicons
# chromosome
python COG_calculations.py accessory_output/chromosome/Aliivibrio_genus/Aliivibrio_genus_95_gene_list_represenative.txt eggnog_mapping/chromosome/Aliivibrio_genus/Aliivibrio_genus.emapper.annotations COG_output/Aliivibrio_chromosome_COG.csv
python COG_calculations.py accessory_output/chromosome/Photobacterium_genus/Photobacterium_genus_95_gene_list_represenative.txt eggnog_mapping/chromosome/Photobacterium_genus/Photobacterium_genus.emapper.annotations COG_output/Photobacterium_chromosome_COG.csv
python COG_calculations.py accessory_output/chromosome/Pseudoalteromonas_genus/Pseudoalteromonas_genus_95_gene_list_represenative.txt eggnog_mapping/chromosome/Pseudoalteromonas_genus/Pseudoalteromonas_genus.emapper.annotations COG_output/Pseudoalteromonas_chromosome_COG.csv
python COG_calculations.py accessory_output/chromosome/Salinivibrio_genus/Salinivibrio_genus_95_gene_list_represenative.txt eggnog_mapping/chromosome/Salinivibrio_genus/Salinivibrio_genus.emapper.annotations COG_output/Salinivibrio_chromosome_COG.csv
python COG_calculations.py accessory_output/chromosome/Vibrio_genus/Vibrio_genus_95_gene_list_represenative.txt eggnog_mapping/chromosome/Vibrio_genus/Vibrio_genus.emapper.annotations COG_output/Vibrio_chromosome_COG.csv

# chromid
python COG_calculations.py accessory_output/chromid/Aliivibrio_genus/Aliivibrio_genus_95_gene_list_represenative.txt eggnog_mapping/chromid/Aliivibrio_genus/Aliivibrio_genus.emapper.annotations COG_output/Aliivibrio_chromid_COG.csv
python COG_calculations.py accessory_output/chromid/Photobacterium_genus/Photobacterium_genus_95_gene_list_represenative.txt eggnog_mapping/chromid/Photobacterium_genus/Photobacterium_genus.emapper.annotations COG_output/Photobacterium_chromid_COG.csv
python COG_calculations.py accessory_output/chromid/Pseudoalteromonas_genus/Pseudoalteromonas_genus_95_gene_list_represenative.txt eggnog_mapping/chromid/Pseudoalteromonas_genus/Pseudoalteromonas_genus.emapper.annotations COG_output/Pseudoalteromonas_chromid_COG.csv
python COG_calculations.py accessory_output/chromid/Vibrio_genus/Vibrio_genus_95_gene_list_represenative.txt eggnog_mapping/chromid/Vibrio_genus/Vibrio_genus.emapper.annotations COG_output/Vibrio_chromid_COG.csv

# megaplasmid
python COG_calculations.py accessory_output/megaplasmid/Pseudoalteromonas_genus/Pseudoalteromonas_genus_95_gene_list_represenative.txt eggnog_mapping/megaplasmid/Pseudoalteromonas_genus/Pseudoalteromonas_genus.emapper.annotations COG_output/Pseudoalteromonas_megaplasmid_COG.csv
python COG_calculations.py accessory_output/megaplasmid/Salinivibrio_genus/Salinivibrio_genus_95_gene_list_represenative.txt eggnog_mapping/megaplasmid/Salinivibrio_genus/Salinivibrio_genus.emapper.annotations COG_output/Salinivibrio_megaplasmid_COG.csv
python COG_calculations.py accessory_output/megaplasmid/Vibrio_genus/Vibrio_genus_95_gene_list_represenative.txt eggnog_mapping/megaplasmid/Vibrio_genus/Vibrio_genus.emapper.annotations COG_output/Vibrio_megaplasmid_COG.csv

# calculating Fisher Exact Test statistics (inner genus rreplicon comparisons)
python COG_fisher_test.py COG_output/Aliivibrio_chromosome_COG.csv COG_output/Aliivibrio_chromid_COG.csv

python COG_fisher_test.py COG_output/Photobacterium_chromosome_COG.csv COG_output/Photobacterium_chromid_COG.csv

python COG_fisher_test.py COG_output/Pseudoalteromonas_chromosome_COG.csv COG_output/Pseudoalteromonas_chromid_COG.csv
python COG_fisher_test.py COG_output/Pseudoalteromonas_chromosome_COG.csv COG_output/Pseudoalteromonas_megaplasmid_COG.csv
python COG_fisher_test.py COG_output/Pseudoalteromonas_chromid_COG.csv COG_output/Pseudoalteromonas_megaplasmid_COG.csv

python COG_fisher_test.py COG_output/Salinivibrio_chromosome_COG.csv COG_output/Salinivibrio_megaplasmid_COG.csv

python COG_fisher_test.py COG_output/Vibrio_chromosome_COG.csv COG_output/Vibrio_chromid_COG.csv
python COG_fisher_test.py COG_output/Vibrio_chromosome_COG.csv COG_output/Vibrio_megaplasmid_COG.csv
python COG_fisher_test.py COG_output/Vibrio_chromid_COG.csv COG_output/Vibrio_megaplasmid_COG.csv













